@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedBiteBook" as VersionedBiteBook MODEL_COLOR
end box

[-> Model : undoBiteBook()
activate Model

Model -> VersionedBiteBook : undo()
activate VersionedBiteBook

VersionedBiteBook -> VersionedBiteBook :resetData(ReadOnlyBiteBook)
VersionedBiteBook --> Model :
deactivate VersionedBiteBook

[<-- Model
deactivate Model

@enduml
